"""Simulation of paracellular ion transport across kidney tubule tight junctions.

Segment-agnostic engine (``engine``) + physics (``physics``) + model objects
(``models``) + plotting (``plotting``), driven by ``Scenario`` configs
(``config``). Currently only Thick Ascending Limb (TAL) scenarios are
defined; adding a new nephron segment means adding new ``Scenario``
instances to ``config.py``, not changing the engine.
"""
from .config import (
    PHYSICAL_CONSTANTS,
    TAL_STATE1,
    TAL_STATE1_5_STRANDS,
    TAL_STATE2_AVG,
    TAL_STATE2_AVG_5_STRANDS,
    TAL_STATE2_PARALLEL,
    TAL_STATE2_PARALLEL_5_STRANDS,
    CompartmentSpec,
    JunctionSpec,
    Pathway,
    PhysicalConstants,
    Scenario,
    SimulationSettings,
)
from .engine import (
    MixingCurve,
    SimulationResult,
    SteadyStateResult,
    build_scenario,
    find_steady_state,
    permeability_mixing_curve,
    run_scenario,
    run_simulation,
    steady_state_for_scenario,
    steady_state_gap,
    transepithelial_potential,
    with_total_time_steps,
)
from .models import Compartment, Junctions
from .physics import (
    EMF,
    calculate_flux,
    calculate_ion_change,
    divalent_membrane_potential,
    goldmann_equation,
    nernst_equation,
    shared_voltage,
)
from .plotting import (
    plot_flow_dynamics,
    plot_ion_dynamics,
    plot_membrane_potential,
    plot_mg_comparison,
    plot_permeability_mixing_curve,
    plot_steady_state_convergence,
    plot_terminal_flux_comparison,
    plot_total_flux_comparison,
    terminal_flow,
    terminal_flow_all_pathways,
    total_flow,
    total_flow_all_pathways,
)

__all__ = [
    "PHYSICAL_CONSTANTS",
    "TAL_STATE1",
    "TAL_STATE1_5_STRANDS",
    "TAL_STATE2_AVG",
    "TAL_STATE2_AVG_5_STRANDS",
    "TAL_STATE2_PARALLEL",
    "TAL_STATE2_PARALLEL_5_STRANDS",
    "CompartmentSpec",
    "JunctionSpec",
    "Pathway",
    "PhysicalConstants",
    "Scenario",
    "SimulationSettings",
    "MixingCurve",
    "SimulationResult",
    "SteadyStateResult",
    "build_scenario",
    "find_steady_state",
    "permeability_mixing_curve",
    "run_scenario",
    "run_simulation",
    "steady_state_for_scenario",
    "steady_state_gap",
    "transepithelial_potential",
    "with_total_time_steps",
    "Compartment",
    "Junctions",
    "EMF",
    "calculate_flux",
    "calculate_ion_change",
    "divalent_membrane_potential",
    "goldmann_equation",
    "nernst_equation",
    "shared_voltage",
    "plot_flow_dynamics",
    "plot_ion_dynamics",
    "plot_membrane_potential",
    "plot_mg_comparison",
    "plot_permeability_mixing_curve",
    "plot_steady_state_convergence",
    "plot_terminal_flux_comparison",
    "plot_total_flux_comparison",
    "terminal_flow",
    "terminal_flow_all_pathways",
    "total_flow",
    "total_flow_all_pathways",
]
